config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost:3000"
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'events#index'
  resources :users, only:[:show] do 
    member do
      get '/:event_id/join_event'  => 'users#user_join_event'
      get '/:event_id/leave_event' => 'users#user_leave_event'
    end
  end
  resources :events do 
    post 'comment' => 'comments#create', as: :comment
    member do 
      get 'like' 
    end

  end
  get 'cancel_own_request/:friend_id' => 'friendships#cancel_own_request', as: :cancel_own_friendship_request
  get 'friends/requests/sent'      => 'friendships#sent_requests',   as: :sent_friendship_requests
  get 'friends/requests/recieved' => 'friendships#recieved_requests', as: :recieved_friendship_requests
  get 'send_request/:friend_id' => 'friendships#send_request', as: :send_friendship_request
  get 'cancel_request/:friend_id' => 'friendships#cancel_request', as: :cancel_friendship_request
  get  'accept_request/:friend_id'   => 'friendships#accept_request', as: :accept_friendship_request
  get '/:id/friends' => 'users#friends', as: :friends
  get '/:id/find_friends' => 'users#find_friends', as: :find_friends 
  get '/:id/my_events'  =>'users#show_my_events', as: :my_events

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

   belongs_to :user , inverse_of: :comments
   belongs_to :event, inverse_of: :comments

   validates :content, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
    
    has_many :guests_events, class_name:"GuestsEvent" ,dependent: :destroy
	has_many :guests, :through => :guests_events, :source => :user
	belongs_to :user, inverse_of: :events
 	mount_uploader :image, AvatarUploader
 	has_many :comments, dependent: :destroy 

 	validates :image,:start_at,:end_at,:image,:disc,:title, presence:true

end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :user
	belongs_to :friend, class_name:"User"	
    

    def sender
    	@user = User.find(self.user_id)
    end

    def reciever
    	@user = User.find(self.friend_id)
    end
end

app/models/guests_event.rb
class GuestsEvent < ApplicationRecord
	belongs_to :event 
	belongs_to :user 
end

app/models/user.rb
class User < ApplicationRecord
# Include default devise modules. Others available are:
# :confirmable, :lockable, :timeoutable and :omniauthable
devise :database_authenticatable, :registerable,
:recoverable, :rememberable, :trackable, :validatable

has_many :comments, dependent: :destroy,inverse_of: :user
has_many :friendships,  class_name:"Friendship", dependent: :destroy
has_many :friends, through: :friendship, dependent: :destroy
has_many :guests_events, class_name:"GuestsEvent"
has_many :events, through: :guests_events, dependent: :destroy
has_many :own_events, class_name:"Event", inverse_of: :user
has_many :sent_requests ,->{where status: "pending"}, class_name: "Friendship"
def recieved_requests
    Friendship.where(friend_id: self.id, status: "pending")
end
def join_event event
    self.guests_events.create!(event_id: event)
end
def leave_event event
    self.guests_events.where(event_id: event).destroy_all
end
def friends
    ids = Array.new
    Friendship.where('(user_id = ? OR friend_id =?) AND (status=?)', self.id, self.id, "accept").map{
        |friendship|
        if friendship.friend_id == self.id
            ids << friendship.user_id
        else
            ids<< friendship.friend_id
        end
    }
    my_friends = User.where(id: ids)                            
end
def has_friendshipable_friends
    ids = Array.new
    Friendship.where('user_id = ? OR friend_id =?', self.id, self.id).map{
        |friendship|
        if friendship.friend_id == self.id
            ids << friendship.user_id
        else
            ids<< friendship.friend_id
        end
    }
    ids << self.id
    return  User.where('id NOT IN (?)', ids.present? ? ids : [self.id])
end

   def is_already_joined event
        GuestsEvent.where(user_id: self.id, event_id: event).present?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception


 before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
  def find_user
  	@current_user = current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	before_action :find_user
def create
	 @comment = Comment.new(find_params)
	 if @comment.save!
	 redirect_to '/' 
	else
		render 'events/index'
	end
end
def find_params
	params[:comment][:user_id] = @current_user.id
	params[:comment][:event_id] = params[:event_id]
	params.require(:comment).permit(:event_id, :content, :user_id)	
end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

before_action :authenticate_user!
before_action :find_event, only:[:show, :destroy, :update, :edit, :like]
before_action :find_user 


def index
	@events  = Event.all.where.not(user_id: @current_user.id).includes(:guests , comments:[:user]).order('updated_at')
end
def show
	@guests = Event.where(id: @event.guest_ids) 
end
def like
	if !@event.likes.include?(@current_user.id)
	    @event.likes << @current_user.id 
	    @event.save
    else
    	@event.likes.delete(@current_user.id)
    	@event.save
    end
    redirect_to '/'
end


def create
	@event = @current_user.own_events.new(find_params)
	if @event.save!
		redirect_to root_path
		flash[:success] = "Event has been succesfully Created"
	else
		render :new
	end
end
def new
	@event = Event.new
end
def update
	if @event.update(find_params)
		redirect_to root_path
		flash[:success] = "Event has been succesfully updated"
	else
		render :edit
	end
end
def destroy
	if @event.destroy
		redirect_to '/'
		flash[:danger]= "Event has been succesfully deleted"
	end
end


private 

def find_event
	@event = Event.find(params[:id])
end
def find_params
	params.require(:event).permit(:title, :disc, :start_at, :end_at, :image)
end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

before_action :authenticate_user!
before_action :find_user 
before_action :find_friendship, only:[:accept_request, :cancel_request ,:cancel_own_request]


def sent_requests
	@sent_requests = @current_user.sent_requests
end

def recieved_requests
	 @recieved_requests = @current_user.recieved_requests
end

def cancel_own_request
	 #@friendship = Friendship.find_by(user_id: @current_user.id, friend_id: params[:friend_id])
     @friendship.destroy
     redirect_to sent_friendship_requests_path
end

def cancel_request
	@friendship.destroy
	redirect_to recieved_friendship_requests_path
end

def accept_request
	@friendship.update_attribute(:status, "accept")
	redirect_to recieved_friendship_requests_path
end
def send_request
	@current_user.friendships.create! friend_id: params[:friend_id], status: "pending"
	redirect_to  find_friends_path(@current_user)
end

def find_friendship
	#@friendship = Friendship.find_by(friend_id: @current_user.id, user_id: params[:friend_id])
    @friendship = Friendship.where("(user_id=? AND friend_id=?) OR (friend_id=? AND user_id=?)", current_user.id, params[:friend_id], current_user.id, params[:friend_id]).first
end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :find_user
before_action :find_params_user, only:[:show, :friends, :user_join_event,:user_leave_event, :show_my_events]
before_action :authenticate_user!
	def show
	end
    def friends
    	@friends = @user.friends
    end
    def find_friends
    	@users = @current_user.has_friendshipable_friends
    end
    def user_join_event
    	@user.join_event(params[:event_id])
    	redirect_to '/'
    end
    def show_my_events
    	@my_events = @user.own_events.includes(:comments, :guests)
    end
    def user_leave_event
    	@user.leave_event(params[:event_id])
    	redirect_to '/'
    end
    def find_params_user
   	   @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<% if @events.present?%>
<div class="panel panel-primary">
       <div class="panel-heading">
          <h3 class="panel-title">
            <span class="badge" style="margin-left:40%;">
       </div>
       <div class="panel-body">
          <div class="well">
             <ul class="list-group">
              <h2>All Events</h2>
           <%@events.each do |event|%>
              <li class="list-group-item" style="margin-top:20px">
                <div class="panel-body">
		              <h2>Event title:  <u><%= event.title %></u></h2>
		               <i>Discription</i>: <%= event.disc%>
		                  <br>
		              <%=image_tag(event.image.url, height:"15%;", width:"15%;") if event.image.present?%>
		                  <br>
                      <%count= event.guests.count%>
                      <%is_already_joined = @current_user.is_already_joined event%>
                      <%if is_already_joined%>
                        <p>you and <%=count%> more people joined this event.</p>
                        <a href="/users/<%= @current_user.id%>/<%=event.id%>/leave_event" class="btn btn-danger btn-xs">Leave</a>
                       <%else%>
                       <%if  count == 0 %>
                  <p>join this event and become first guest for this event in your friends.</p>
                  <%else%>
                  <p><%= count %> people already joined this event.</p>
                  <%end%>
                    <a href="/users/<%= @current_user.id%>/<%=event.id%>/join_event" class="btn btn-success btn-xs">Join</a>

                      <%end%> 

                      <%if is_already_joined%>
                      <a href="/events/<%=event.id%>/like" class="btn btn-success btn-xs">Like</a> <%=event.likes.size%>
                      
                          </br>
		              created by :<%= event.user.username%>
                  Comments:
              <ul class="list-group">
                <%comments = event.comments%>
                <% if comments.present?%>
                      <% comments.each do |comment|%>
                       <li class="list-group-item">
                         <div style="word-break:break-all;">
                          <%= comment.content%>
                          <br>
                          <span class="badge">
                            Commented By:<%= comment.user.username%></span> 
                          </div>
                          </li>
                      <%end%>
                <%end%>
                  <%= @current_user.username%>
                  <%= form_for :comment, :url=> event_comment_path(event) do |f|%>
                  <%= f.text_area :content, required:true %><br>
                  <%= f.submit "Submit" %>
                  <%end%> 
                  <%end%>
              </ul>

















           	    </div>
      	      </li>
            <% end %>
            </u>
          </div>
      </div>
  </div>
<% else %>
<h4>
  No Post Available ..<%=link_to"Create New Event", new_event_path%>
</h4>
<%end%>

app/views/events/new.html.erb
<h2>Create new event</h2>

<%= form_for @event do |f| %>
    <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, autofocus: true ,required: true%>
    </div>

  <div class="field">
    <%= f.label :disc %><br />
    <%= f.text_area :disc, autofocus: true,required: true %>
  </div>
   <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image, autofocus: true ,required: true%>
  </div>
   <div class="field">
    <%= f.label :start_at %><br />
    <%= f.date_select :start_at, autofocus: true ,required: true%>
  </div>
   <div class="field">
    <%= f.label :end_at %><br />
    <%= f.date_select :end_at, autofocus: true ,required: true%>
  </div>
  <div class="actions">
    <%= f.submit "Create New Event" %>
  </div>
<% end %>

app/views/friendships/recieved_requests.html.erb
<% if @recieved_requests.present?%>
<div class="panel panel-primary">
       <div class="panel-heading">
          <h3 class="panel-title">
            <span class="badge" style="margin-left:40%;">
       </div>
       <div class="panel-body">
          <div class="well">
             <ul class="list-group">
              <h2>Recieved Friend Requests </h2>
				<%@recieved_requests.each do|request|%>
         <li class="list-group-item">
          <%sender = request.sender%>
					<%=sender.username%> <a href="/accept_request/<%=sender.id%>" class="btn btn-success btn-xs">Confirm</a>
           <a href="/cancel_request/<%=sender.id%>" class="btn btn-success btn-xs">Delete Request</a>
        </br></li>
					<%end%>
            </u>
          </div>
      </div>
  </div>
<% else %>
<h4> No Recieved Request Yet!
</h4>
<%end%>

app/views/friendships/sent_requests.html.erb
<% if @sent_requests.present?%>
<div class="panel panel-primary">
       <div class="panel-heading">
          <h3 class="panel-title">
            <span class="badge" style="margin-left:40%;">
       </div>
       <div class="panel-body">
          <div class="well">
             <ul class="list-group">
              <h2>Sent Friend Request </h2>
				<%@sent_requests.each do|request|%>
         <li class="list-group-item">
          <%reciever = request.reciever %>
					<%=reciever.username %> &nbsp;&nbsp;&nbsp;&nbsp;<a href="/cancel_own_request/<%=reciever.id%>" class="btn btn-danger btn-xs"> Cancel</a></br></li>
					<%end%>
            </u>
          </div>
      </div>
  </div>
<% else %>
<h4>
	NO Sent Request Yet!
</h4>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>GroupPostApp</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<%@current_user = current_user%>
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
				</button>

      <a class="navbar-brand" href="/">Group-Post-App</a>
				
			</div>
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
				<ul class="nav navbar-nav">
					<% if @current_user %>
					<li>
						<div class="navbar-brand">
							Signed In As : <i><%= link_to "#{@current_user.username}",user_path(@current_user)%></i>
						</div>
					</li>
				

                       <li class="active"><a href="/"> Home <span class="sr-only">(current)</span></a></li>
                        <li><a href="/events/new"> Create New Events </a></li>
					
					<li><%=link_to"My Events", my_events_path(@current_user)%></li>
					<li><%=link_to"Friends", friends_path(@current_user)%></li>
					



					<li class="dropdown open">
          <a href="/friends/requests/sent" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Friend requests <span class="caret"></span></a> 

          <ul class="dropdown-menu" role="menu">
            <li><a href="/friends/requests/sent">sent requests</a></li>
            <li><a href="/friends/requests/recieved">recivece requests</a></li>
        </ul>
        </li>
					<li><%=link_to"Find Friends", find_friends_path(@current_user) %></li>


					<% end %>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<% if @current_user %>
					 <li>
						<%= link_to "Log Out", destroy_user_session_path, method: :delete %>
					 </li>
					<% else %>
								<li><%= link_to "Log In" , new_user_session_path%></li>
								<li><%= link_to "Sign Up" ,user_session_path%></li>
					<% end %>
							</ul>
						</div><!-- /.navbar-collapse -->
					</div><!-- /.container-fluid -->
				</nav>
				<div class="container">
					<div class="error-flash"><%= notice%></div>
					<%= yield %>
				</div>
			</body>
			</html>
            

app/views/users/find_friends.html.erb
<% if @users.present?%>
<div class="panel panel-primary">
       <div class="panel-heading">
          <h3 class="panel-title">
            <span class="badge" style="margin-left:40%;">
       </div>
       <div class="panel-body">
          <div class="well">
             <ul class="list-group">
              <h2>People you may be know </h2>
  				<%@users.each do|user|%>
         <li class="list-group-item">
					<%=link_to "#{user.username}", user_path(user)%> &nbsp;&nbsp;&nbsp;&nbsp; 
          <a href="/send_request/<%=user.id%>" class="btn btn-success btn-xs">Add</a></br></li>
					<%end%>
            </u>
          </div>
      </div>
  </div>
<% else %>
<h4>
</h4>
<%end%>

app/views/users/friends.html.erb
<% if @friends.present?%>
<div class="panel panel-primary">
       <div class="panel-heading">
          <h3 class="panel-title">
            <span class="badge" style="margin-left:40%;">
       </div>
       <div class="panel-body">
          <div class="well">
             <ul class="list-group">
              <h2>Your Friend List </h2>
  				<%@friends.each do|friend|%>
         <li class="list-group-item">
					<%=link_to "#{friend.username}", user_path(friend)%> &nbsp;&nbsp;&nbsp;&nbsp; 
          <a href="/cancel_request/<%=friend.id%>" class="btn btn-success btn-xs">remove</a></br></li>
					<%end%>
            </u>
          </div>
      </div>
  </div>
<% else %>
<h4>
</h4>
<%end%>

app/views/users/show.html.erb
<h2>Profile </h2>


  <div class="field">
Email:    <%= @user.email %><br />
  </div>

  <div class="field">
   Username: <%= @user.username %><br />
  </div>
  <%if @current_user.id == @user.id%>
  <div class="actions">
     <%=link_to "Edit Your Profile",edit_user_registration_path(@user)%>      
  </div>
<h3>Cancel my account</h3>

<p>Unhappy? <%= button_to "Cancel my account", registration_path(@user), data: { confirm: "Are you sure?" }, method: :delete %></p>
<%end%>
<%= link_to "Back", :back %>

app/views/users/show_my_events.html.erb
<% if @my_events.present?%>
<div class="panel panel-primary">
       <div class="panel-heading">
          <h3 class="panel-title">
            <span class="badge" style="margin-left:40%;">
       </div>
       <div class="panel-body">
          <div class="well">
             <ul class="list-group">
              <h2>All Events</h2>
           <%@my_events.each do |event|%>
              <li class="list-group-item" style="margin-top:20px">
                <div class="panel-body">
		              <h2>Event title:  <u><%= event.title %></u></h2>
		               <h5><i>Discription</i><h5> : <%= event.disc%>
		                  <br>
		              <%=image_tag(event.image.url, height:"15%;", width:"15%;") if event.image.present?%>
		                  <br>
                      <%count = event.guests.count%>
                      <%if count >0%>
                       <p><%= count %> people joined your event.
                      <%end%>
		                  <a href="#" class="btn btn-danger btn-xs">Delete</a>
                          </br>
           	    </div>
      	      </li>
            <% end %>
            </u>
          </div>
      </div>
  </div>
<% else %>
<h4>
  No Events are Available...<%=link_to"Create Your First Event", new_event_path%>
</h4>
<%end%>